name: trademe_repository
description: Dart package which manages interaction with Trademe.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.3
  oauth1: ^1.0.4
  http: ^0.12.2
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
